import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise", "vitest"],
  options: {
    typeAware: true,
  },
  categories: {
    correctness: "error",
    suspicious: "warn",
    perf: "error",
    style: "warn",
  },
  rules: {
    "no-map-spread": "off",
    "no-named-export": "off",
    "no-magic-numbers": "off",
    "consistent-indexed-object-style": "off",
    "id-length": "off",
    "no-await-expression-member": "off",
    "max-nested-calls": "off",
    "sort-keys": "off",
    curly: "off",
    "switch-case-braces": "off",
    "vitest/require-hook": "off",
    "no-ternary": "off",
    "group-exports": "off",
    "exports-last": "off",
    "prefer-default-export": "off",
    "no-null": "off",
    "consistent-type-specifier-style": "off",
    "max-statements": "off",
    "consistent-type-imports": "error",
    "relative-url-style": ["error", "always"],
    "no-namespace": "off",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "func-style": "off",
    "sort-imports": [
      "error",
      {
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
      },
    ],
    "new-cap": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/avoid-new": "off",
    "prefer-await-to-then": "off",
    "max-params": "off",
    "no-underscore-dangle": "off",
    "no-nested-ternary": "off",
    "unicorn/no-nested-ternary": "off",
    "no-anonymous-default-export": "off",
    "no-continue": "off",
    "init-declarations": "off",
    "prefer-to-be-truthy": "off",
    "vitest/prefer-expect-assertions": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/no-importing-vitest-globals": "error",
    "vitest/require-top-level-describe": "off",
    "vitest/max-expects": "off",
    "vitest/no-hooks": "off",
  },
  overrides: [
    {
      files: ["*.test.ts", "*.spec.ts"],
      rules: {
        "@typescript-eslint/no-explicit-any": "off",
      },
    },
    {
      files: ["*-definitions.ts"],
      rules: {
        "no-unused-vars": "off",
        "@typescript-eslint/no-redundant-type-constituents": "off",
        "@typescript-eslint/no-duplicate-type-constituents": "off",
        "group-exports": "off",
        "exports-last": "off",
        "consistent-indexed-object-style": "off",
      },
    },
    {
      files: ["bin/*.mjs", "src/cmd.mjs"],
      rules: {
        "import/no-nodejs-modules": "off",
        "prefer-destructuring": "off",
      },
    },
  ],
});
