import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise"],
  options: {
    typeAware: true,
  },
  // Generated by `api-types`; there is nothing to fix by hand.
  ignorePatterns: ["**/__definitions__/**"],
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
    style: "error",
  },
  rules: {
    // Judge a wrapped comment by its first line, so the second can carry on the sentence.
    "capitalized-comments": ["error", "always", { ignoreConsecutiveComments: true }],
    "no-map-spread": "off",
    "no-named-export": "off",
    "no-magic-numbers": "off",
    "consistent-indexed-object-style": "off",
    "id-length": "off",
    "no-await-expression-member": "off",
    "max-nested-calls": "off",
    "sort-keys": "off",
    curly: "off",
    "switch-case-braces": "off",
    "no-ternary": "off",
    "group-exports": "off",
    "exports-last": "off",
    "prefer-default-export": "off",
    "no-null": "off",
    "consistent-type-specifier-style": "off",
    "max-statements": "off",
    "relative-url-style": ["error", "always"],
    "no-namespace": "off",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "func-style": "off",
    "sort-imports": [
      "error",
      {
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
      },
    ],
    "new-cap": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/avoid-new": "off",
    "prefer-await-to-then": "off",
    "max-params": "off",
    "no-underscore-dangle": "off",
    "no-nested-ternary": "off",
    "unicorn/no-nested-ternary": "off",
    "no-anonymous-default-export": "off",
    "no-continue": "off",
    "init-declarations": "off",
    "unicorn/number-literal-case": "off",
    "eslint/one-var": "off",
    // A ternary only reads better when both branches fit on one line.
    "unicorn/prefer-ternary": ["error", "only-single-line"],
    "unicorn/prefer-spread": "off", // Upstream bug
    // Positional capture groups are used throughout; naming them all would
    // reindex every `match[n]` consumer for no functional gain.
    "eslint/prefer-named-capture-group": "off",
    // Stylesheets can only be pulled in for their side effects.
    "import/no-unassigned-import": ["error", { allow: ["**/*.css", "**/*.scss"] }],
    // Bug-catching rules oxc files under pedantic or restriction, which are not enabled wholesale.
    "typescript/no-misused-promises": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/only-throw-error": "error",
    "eslint/array-callback-return": "error",
    "typescript/no-deprecated": "error",
    "eslint/eqeqeq": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-dynamic-delete": "error",
    "import/no-cycle": "error",
    "eslint/no-empty": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
  },
  overrides: [
    {
      // Mocks and page factories are test code too, and use vitest.
      files: [
        "*.test.ts",
        "*.test.tsx",
        "*.spec.ts",
        "*.spec.tsx",
        "e2e/**",
        "**/__mocks__/**",
        "**/__factories__/**",
      ],
      plugins: ["vitest"],
      rules: {
        "vitest/require-hook": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-expect-assertions": "off",
        "vitest/prefer-importing-vitest-globals": "off",
        "vitest/prefer-describe-function-title": "off",
        "vitest/require-top-level-describe": "off",
        "vitest/max-expects": "off",
        "vitest/no-hooks": "off",
        "vitest/prefer-called-once": "off",
        // `toEqual` ignores keys written as `undefined`; `toStrictEqual` does not. Fixtures
        // spell those out on purpose, so the fix changes what a test asserts.
        "vitest/prefer-strict-equal": "off",
        // `vi.mock(import("x"))` does not type-check against vi.mock's overloads.
        "vitest/prefer-import-in-mock": "off",
        // A mock standing in for a whole module would restate that module's signatures.
        "vitest/require-mock-type-parameters": "off",
        // Assertion helpers are named `expect…` or `assert…` (`expectRedirect`), or are
        // page-object methods that wrap expect(), so it can see them; anything left over
        // really asserts nothing.
        "vitest/expect-expect": [
          "error",
          { assertFunctionNames: ["expect*", "assert*", "page.expect*", "page.*Present"] },
        ],
        "vitest/prefer-lowercase-title": "off",
        // Tests stash a method to restore it after stubbing. It is never called, so
        // `this` never matters.
        "unbound-method": "off",
        // A helper belongs next to the only test that uses it; hoisting it to module
        // scope saves nothing in a test run and puts it out of sight.
        "unicorn/consistent-function-scoping": "off",
        "vitest/no-conditional-expect": "off",
        "vitest/prefer-called-with": "off",
        "prefer-arrow-callback": "off",
        "vitest/consistent-vitest-vi": "off", // Upstream bug
        "vitest/consistent-test-filename": "off",
        // UI steps, polling and findBy queries are sequential by design.
        "eslint/no-await-in-loop": "off",
      },
    },
    {
      files: ["bin/*.mjs", "src/cmd.mjs", "src/openapi-typescript.mjs"],
      rules: {
        "import/no-nodejs-modules": "off",
        "prefer-destructuring": "off",
      },
    },
  ],
});
