blockExoticSubdeps: true

ignoreScripts: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - jwk-subtle
  - pbkdf-subtle
  - eslint-config-two-stroke

patchedDependencies:
  openapi-typescript: patches/openapi-typescript.patch

trustPolicy: no-downgrade
