runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: corepack enable
      shell: bash

    - run: yarn install
      shell: bash
      env:
        NPM_AUTH_TOKEN: fake
