name: CI

on: [push]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/install

      - run: yarn eslint
        env:
          NPM_AUTH_TOKEN: fake
